# Document:
# http://simiki.org/docs/configuration.html

url: bytemarvel.github.io
title: Lintaofang's Personal Wiki
keywords:  Data Mining
description: everthing about me
author: Lintaofang
root: /wiki
deploy:
  - type: git
    remote: origin
    branch: gh-pages
default_ext: md
pygments: true
debug: false
theme: simple
